### ISSUE TITLE
Info button disappears if tapped rapidly

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#1]
If the Info button is tapped before the presentation completes, it seems to disappear until the screen is navigated to again

**Comment by AnneSkov** [comment]
https://user-images.githubusercontent.com/93835944/154809140-f1720aed-27ba-4d07-bc2b-58cca28cf123.mp4

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/e76d68d4b13167a6bf6b103a6454bb29aa201f2c
