### ISSUE TITLE
Subtitle should be displayed as a label under titel

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#10]
The subtitle for each question should be shown in parentheses not as a placeholder in the text fields. Maybe also reduce the distance between the titles and text fields by a little bit

Here's an example of how it looks on iOS:
![IMG_8076](https://user-images.githubusercontent.com/93835944/154835607-e73b0665-bbbd-4096-9e2a-b8b08bfe2b40.PNG)

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/417c47066d113fb20b2f2cb44ae9b0dc2cb72f7c
