### ISSUE TITLE
Various issues with notifications

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#12]
We tried setting some notifications and it looks like only some of them show up (And without buzzing the phone or waking the screen)

The title of the notification should be the titel of the plan. It also looks like you are missing a notification icon, if you send us the requirements, we can make it for you.

There should also be a indication on the list of plans that show when there's a notification set

Here's some examples from iOS:
![IMG_8077](https://user-images.githubusercontent.com/93835944/154836092-d450c0aa-5dd8-4038-847c-c3b4f90390c3.PNG)
![IMG_8078](https://user-images.githubusercontent.com/93835944/154836093-480bdd55-1e3b-4c2e-8d46-1d045983be85.PNG)

**Comment by Albyzai** [comment]
fixed all except for the notification icon in 4b26b34015fe9a8ceeb7d6b9b312f26d2633760c, a41f8e661ff304b44a38447a27b3d64f855c3ef9, 463867432f15496f285a766ce3e5e7e6261f98bf, b757561d3d09b7458d62884cf2482fff0e248fe6
