### ISSUE TITLE
Repeat title and subtitle of question in pdf if row breaks page

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#13]
It would be great if the titel and subtitle of a question could be repeated if a question row spans multiple pages in the exported PDF (If it's possible without spending too much time on it)

**Comment by Albyzai** [comment]
made in https://github.com/overlevelsesguiden/The10H-Android/commit/7216fe71a3b0754b81b29ccc4fe8790a1be3044e
