### ISSUE TITLE
Color of buttons in delete plan confirmation

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#14]
The color of the cancel button makes it look disabled in the dialog asking confirmation to delete a plan. Looking around a bit in Android system apps, it looks like it's common to have both the cancel and confirm button have the same color (In our case orange)

Here's an example from Google calendar:
![Screenshot_20220220-103003](https://user-images.githubusercontent.com/93835944/154836669-02fd7ba0-9b00-44d0-8c16-b8c7f29a8ad3.jpg)

**Comment by Albyzai** [comment]
Fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/657b024b3ba716ce13d139dc6c4a7889861ce494
