### ISSUE TITLE
Tapping notification doesn't open the plan

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#19]
Nothing seems to happen when tapping a notification.

Expected behavior:
After tapping a notification, the app should go to the foreground (if it isn't already) and navigate to the plan associated with the notification

**Comment by Albyzai** [comment]
On it, completely forgot about it.

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/65570839efd5953750df8ef50cb6338572240b8d
