### ISSUE TITLE
Underline under title after editing

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#2]
After typing in a title and tapping a different text field, the underline persist in the title label

![Screenshot_20220219-171829](https://user-images.githubusercontent.com/93835944/154809256-4639cc98-8b20-4363-b1eb-f8f5c0eb393c.jpg)

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/25da091b28cdbe20c9c36b194af64fe3db8fcd13
