### ISSUE TITLE
Changing the alarm time dose not unschedule previous alert time

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#22]
After setting a notification time and saving, then editing it to a different time, dose not prevent a notification from being sent on the previous selected time.

What I did:

1. Tapped edit on a plan
2. Set a notification for 12:00 and saved
3. Went to change the notification to 12:01 and saved
4. Went to change the notification to 11:59 and saved

I got a notification at 11:59, 12:00 and 12:01. The bell icon on the list and the dot on the bell in edit mode was also present after the notification on 11:59 as well as the notification "on/off switch"

Expected result:
I should only get a notification at 11:59, the bell should disappear at 11:59 and the toggle switch should be off in edit mode

**Comment by Albyzai** [comment]
should be fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/8098daea1d775e49fa6dd1e9b8fb89dd1239382c
