### ISSUE TITLE
Plan preview shows unsaved data after edit

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#24]
Steps to reproduce:

1. Start the app
2. Save plan
3. Open the plan to edit, and fill in one text field
4. Tap on back
5. In the plan preview - you will see the unsaved data
6. If you go back to the plan list and then back to preview, the unsaved data is gone

https://user-images.githubusercontent.com/7668264/160300748-cd43a83b-1aa8-48b5-b81f-06dba9995e60.mp4

Reported by Ziv

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/27dd087814dbaecb08b084ecae3ae9ebc8036227
