### ISSUE TITLE
Share as PDF crashes the app

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#25]
Steps to reproduce:

1. Start the app
2. Write a plan with a title that has many emojis
3. Save the plan
4. Try to share the plan as PDF with only the filled fields
5. App will crash

https://user-images.githubusercontent.com/7668264/160300783-925bf097-9ab2-4aa1-9a13-6e520e127075.mp4

Reported by Ziv

**Comment by Albyzai** [comment]
Cannot reproduce. Also feels like major scope creep, considering it is an edge case.
![image](https://user-images.githubusercontent.com/16287560/160931237-c5ac3379-ac8d-45b1-b7eb-83ef693c97e2.png)

**Comment by Marzhel** [comment]
I tried to re-produce and on a OnePlus and it appers to work fine. Closing
