### ISSUE TITLE
Support migrating data from old version

### ISSUE THREAD

**Issue by Marzhel** [overlevelsesguiden/The10H-Android#28]
We have to make sure people that update the app don't loose any data when installing the new version of the app. I went through the old code and found the format used for date and time information:

Each plan has a `date` and a `time` field, the date field stores the date in the following format: `dd:MM:yyyy` and the time field is stored in the following format: `HH:mm`. No information is stored regarding seconds or time zone. 

My recommendation would be to create a new string combining the `date` and `time` field, correcting the separators to follow the ISO 8601 standard, setting seconds to 00 and the time zone to the devices current one and use it to create whatever time zone compatible timestamp object appropriate for android development

```
{
    "date": "10:04:2022",
    "time": "17:13",
    ...
}
```

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/656df620b4089739369262c16bf14b8d91a55557
