### ISSUE TITLE
Text input lost on device rotation

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#3]
Maybe just disallow rotation, if it's difficult to fix

https://user-images.githubusercontent.com/93835944/154809491-738a9973-4e9b-474f-98b3-bdc4309ef6e9.mp4

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/d4c6fd72706049b55a5f15aceaa893c1ad1fa6eb by disallowing landscape mode. Lmk if screen landscape is important.
