### ISSUE TITLE
"Luk" button appears disabled in alarm dialog

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#6]
Maybe it's not necessary to have both a save and a close button

![Screenshot_20220219-173727](https://user-images.githubusercontent.com/93835944/154809921-8b36f4da-942f-461d-9c81-ad9918f91ea9.jpg)

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/657b024b3ba716ce13d139dc6c4a7889861ce494
