### ISSUE TITLE
Question 2 has wrong title

### ISSUE THREAD

**Issue by AnneSkov** [overlevelsesguiden/The10H-Android#9]
The title of the second question is set to the subtile. It should be "Hvorfor skal jeg lave det?"

![Screenshot_20220220-095915](https://user-images.githubusercontent.com/93835944/154835535-9323a529-68a1-4dab-a1c3-4cb729328588.jpg)

**Comment by Albyzai** [comment]
fixed in https://github.com/overlevelsesguiden/The10H-Android/commit/ed0159c8b7e6a7bf70b596c299836595635d67d7
